spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d0d73c593b70acdb761f
            clientSecret: 345fd2ef6f0b01ad5269b4f94fb612b926af8004
            #redirect-uri: http://localhost:8005/login/oauth2/code/github
          google:
            client-id: 683933642455-ersut06o300kurrf1ec2ckkktd6n8oru.apps.googleusercontent.com
            client-secret: IDDzj9A3IgjPz0pegeBge-tu
            #redirect-uri: http://localhost:8005/login/oauth2/code/google  application:    name: OAuth2-Server  jpa:    hibernate:      ddl-auto: update  datasource:    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db    username: direct    password: s$cret
    
server:  port: 8005


# ...